import { useEffect, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { Backdrop, CircularProgress, Container } from '@mui/material';

import { useMetaMask } from 'metamask-react';

import { EscrowData, EscrowTable, MetaMaskConnectCard } from '@components';

import { BigNumber } from 'ethers';
import { mapApiEscrowToEscrow } from 'utils';

const escrows_fetched: EscrowData[] = [
  {
    escrowIndex: BigNumber.from(0),
    XOwner: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    XAssetAddress: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    XAmount: BigNumber.from(0),
    YOwner: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    YAssetAddress: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    YAmount: BigNumber.from(0),
    closed: false,
  },
  {
    escrowIndex: BigNumber.from(1),
    XOwner: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    XAssetAddress: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    XAmount: BigNumber.from(0),
    YOwner: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    YAssetAddress: '0x2d71c4144b58c640197EC0970A5bA09C2DfA062a',
    YAmount: BigNumber.from(0),
    closed: false,
  },
];

const TradeListPage: NextPage = () => {
  const { status, connect, account, chainId, ethereum } = useMetaMask();

  const [openBackdrop, setOpenBackdrop] = useState(false);
  const [escrows, setEscrows] = useState([] as EscrowData[]);

  useEffect(() => {
    if (status !== 'connected') {
      setEscrows([]);
      return;
    }

    setOpenBackdrop(true);
    const getEscrowsPromise = axios.get(process.env.NEXT_PUBLIC_BACKEND_BASE_URL + '/api/trades?qOffset=0&qLimit=10').then(({ data }) => {
      setEscrows(data.map(mapApiEscrowToEscrow));
      setOpenBackdrop(false);
    });

    return () => {
      setEscrows([]);
      setOpenBackdrop(false);
    }
  }, [status, chainId]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Backdrop open={openBackdrop}>
        <CircularProgress />
      </Backdrop>

      <MetaMaskConnectCard />

      <Container style={{ display: status === 'connected' ? 'flex' : 'none' }}>
        <EscrowTable escrows={escrows} />
      </Container>
    </Container>
  );
}

export default TradeListPage;
