import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { Avatar, Backdrop, Button, Card, CardActions, CardContent, CircularProgress, Container, Stack, Typography } from '@mui/material'
import { useMetaMask } from 'metamask-react'

const AssetCard = ({ index, item }: { index: number, item: any }) => {
  return(
    <Card id={`assets_${index}`} sx={{ display: 'grid' }}>
      <Avatar>{item.shortName}</Avatar>
      <CardContent sx={{ display: 'grid' }}>
        <Typography>{item.shortName}</Typography>
        <Typography>{item.displayName}</Typography>
        <Typography>{item.price} $</Typography>
        <Typography>{item.count}</Typography>
      </CardContent>
    </Card>
  );
}

const assets_connected: any[] = [
  {
    shortName: 'ETH',
    displayName: 'Ethereum',
    price: 3000.0,
    count: 0.0,
  },
  {
    shortName: 'KAL',
    displayName: 'Kal Token',
    price: 0.0,
    count: 100.0,
  },
];

const Home: NextPage = () => {
  const { status, connect, account, chainId, ethereum } = useMetaMask();

  const [openBackdrop, setOpenBackdrop] = React.useState(false);
  const [assets, setAssets] = React.useState([] as JSX.Element[]);

  React.useEffect(() => {
    if (status === 'connected') {
      setOpenBackdrop(true);
      const timeout = setTimeout(() => {
        setAssets(assets_connected);
        setOpenBackdrop(false);
      }, 1000);
      return () => {
        setAssets([]);
        setOpenBackdrop(false);
        clearTimeout(timeout);
      };
    }
    setAssets([]);
  }, [status]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        {
          'initializing': <Card sx={{ maxWidth: 360 }}>
            <CardContent>
              <Typography gutterBottom variant='h5' component='div'>{status}</Typography>
              <Typography variant='body2' color='text.secondary'>
                Synchronization with MetaMask ongoing...
              </Typography>
            </CardContent>
          </Card>,
          'unavailable': <Card sx={{ maxWidth: 360 }}>
            <CardContent>
              <Typography gutterBottom variant='h5' component='div'>{status}</Typography>
              <Typography variant='body2' color='text.secondary'>
                MetaMask not available :(
              </Typography>
            </CardContent>
          </Card>,
          'notConnected': <Card sx={{ maxWidth: 360 }}>
            <CardContent>
              <Typography gutterBottom variant='h5' component='div'>{status}</Typography>
              <Typography variant='body2' color='text.secondary'>
                Not connected
              </Typography>
            </CardContent>
            <CardActions>
              <Button onClick={connect}>Connect to MetaMask</Button>
            </CardActions>
          </Card>,
          'connecting': <Card sx={{ maxWidth: 360 }}>
            <CardContent>
              <Typography gutterBottom variant='h5' component='div'>{status}</Typography>
              <Typography variant='body2' color='text.secondary'>
                Connecting...
              </Typography>
            </CardContent>
          </Card>,
          'connected': <Card sx={{ maxWidth: 360 }}>
            <CardContent>
              <Typography gutterBottom variant='h5' component='div'>{status}</Typography>
              <Typography variant='body2' color='text.secondary'>
                Connected account {account} on chain ID {chainId}
              </Typography>
            </CardContent>
          </Card>,
        }[status]
      }

      <Backdrop open={openBackdrop}>
        <CircularProgress />
      </Backdrop>

      <Stack display='grid'>
        {assets.map((item, index) => <AssetCard index={index} item={item}></AssetCard>)}
      </Stack>
    </Container>
  )
}

export default Home
