import { useEffect, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { Backdrop, CircularProgress, Container } from '@mui/material'
import axios from 'axios';

import { useMetaMask } from 'metamask-react'

import { AssetData, AssetTable, MetaMaskConnectCard, NavBar } from '@components';

import { mapApiAssetToAsset } from 'utils';

const Home: NextPage = () => {
  const { status, connect, account, chainId, ethereum } = useMetaMask();

  const [openBackdrop, setOpenBackdrop] = useState(false);
  const [assets, setAssets] = useState([] as AssetData[]);

  useEffect(() => {
    if (status === 'connected') {
      setOpenBackdrop(true);
      const balancePromise = axios.get(process.env.NEXT_PUBLIC_BACKEND_BASE_URL + `/api/balance?wallet=${account}`).then(({ data }) => {
        setAssets(data.map(mapApiAssetToAsset));
        setOpenBackdrop(false);
      });
      return () => {
        setAssets([]);
        setOpenBackdrop(false);
      };
    }
    setAssets([]);
  }, [status, chainId]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Backdrop open={openBackdrop}>
        <CircularProgress />
      </Backdrop>

      <NavBar />

      <MetaMaskConnectCard />

      <Container style={{ display: status === 'connected' ? 'flex' : 'none' }}>
        <AssetTable assets={assets} />
      </Container>
    </Container>
  )
}

export default Home
