import React, { useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useMetaMask } from 'metamask-react';
import { Container } from '@mui/material';
import abiInterface from '../contract';
import MetamaskConnectCard from '../components/MetamaskConnectCard';

const TradePage: NextPage = () => {
  const router = useRouter();
  const { YAddress, TokenX, TokenY } = router.query;
  const { status, connect, account, chainId, ethereum } = useMetaMask();

  const swap2p = '0x2512444b85715F383eE3a17bCB40eCE0C9723ea6';

  useEffect(() => {
    if (status === 'connected') {
      const data = abiInterface.encodeFunctionData('createEscrow', [TokenX, 0, TokenY, 0, YAddress]);
      console.log(data);
      // const sendObj = ethereum.request({
      //   method: 'eth_sendTransaction',
      //   params: [{
      //     to: swap2p,
      //     from: ethereum.selectedAddress,
      //     value: '0x00',
      //     chainId: chainId,
      //     data,
      //   }],
      // }).then(console.log).catch(console.log);
    }
  }, [status]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MetamaskConnectCard />
    </Container>
  );
};

export default TradePage;
